class HighPrecisionSystemError(Exception): ...
class HighPrecisionTypeError(Exception): ...
class HighPrecisionValueError(Exception): ...
class HighPrecisionFloatingPointError(ArithmeticError): ...
class HighPrecisionOverflowError(ArithmeticError): ...
class HighPrecisionZeroDivisionError(ArithmeticError): ...
class HighPrecisionModuleNotFoundError(ImportError): ...
class HighPrecisionIndexError(LookupError): ...
class HighPrecisionKeyError(LookupError): ...
class HighPrecisionUnboundLocalError(NameError): ...

class HighPrecisionBlockingIOError(OSError):
    characters_written: int

class HighPrecisionChildProcessError(OSError): ...
class HighPrecisionConnectionError(OSError): ...
class HighPrecisionBrokenPipeError(ConnectionError): ...
class HighPrecisionConnectionAbortedError(ConnectionError): ...
class HighPrecisionConnectionRefusedError(ConnectionError): ...
class HighPrecisionConnectionResetError(ConnectionError): ...
class HighPrecisionFileExistsError(OSError): ...
class HighPrecisionFileNotFoundError(OSError): ...
class HighPrecisionInterruptedError(OSError): ...
class HighPrecisionIsADirectoryError(OSError): ...
class HighPrecisionNotADirectoryError(OSError): ...
class HighPrecisionPermissionError(OSError): ...
class HighPrecisionProcessLookupError(OSError): ...
class HighPrecisionTimeoutError(OSError): ...
class HighPrecisionNotImplementedError(RuntimeError): ...
class HighPrecisionRecursionError(RuntimeError): ...
class HighPrecisionIndentationError(SyntaxError): ...
class HighPrecisionTabError(IndentationError): ...
class HighPrecisionUnicodeError(ValueError): ...

class HighPrecisionMathError(Exception):...
class HighPrecisionLengthError(Exception):...
class HighPrecisionBinError(Exception):...